_Name_ = input("what is your name: ")
_Age_ = int(input("what year were you born: "))
_Hobby_ = input("what is your favorite hobby: ")
print("=" * 30)
print("Player Card")
print("=" * 30)
print(_Name_.capitalize)
print(2026 - _Age_)
print(_Hobby_)
print("-" * 30)
print("Thank you for creating your profile")
print("=" * 30)